version: 2.1
orbs:
  gcp-cli: circleci/gcp-cli@1.8.4
executors:
  node:
    docker:
      - image: circleci/node:10
workflows:
  build_and_deploy:
    jobs:
      - build
      - deploy:
          context: gcloud-creds
          filters:
            branches:
              only: master
jobs:
  build:
    executor: node
    steps:
      - checkout
      - run: npm install
      - run: npm run build
  test:
    executor: node
    steps:
      - checkout
      - run: npm install
      - run: npm run test
  deploy:
    executor: node
    steps:
      - checkout
      - gcp-cli/install
      - gcp-cli/initialize
      - run: npm i
      - run: npm run build
      - run: cd dist && gcloud app deploy
